package fitnesscampsystem;

import DataBase.Database;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import panels.Add_Member;
import panels.Members;
import panels.Members_Information;
import panels.Monthly_Reports;
import panels.Register;

public class Main_Frame_Admin extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    DefaultTableModel dm;

    GridBagLayout layout = new GridBagLayout();
    Register p1;
    Add_Member p2;
    Monthly_Reports p3;
    Members p4;
    Members_Information p5;

    static boolean maximized = true;

    public Main_Frame_Admin() {
        initComponents();
        con = Database.ConnectDB();
        

        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        p1 = new Register();
        p2 = new Add_Member();
        p3 = new Monthly_Reports();
        p4 = new Members();
        p5 = new Members_Information();

        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();

        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(p1, c);

        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(p2, c);

        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(p3, c);

        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(p4, c);

        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(p5, c);

        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);

        
        members_table_update();
    }

    Main_Frame_Admin(String un) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void members_table_update() {

        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
            Calendar c = Calendar.getInstance();
            c.set(Calendar.DAY_OF_MONTH, 1);
            c = Calendar.getInstance(); // reset
            String today = dateFormat.format(c.getTime());
            String sql = "SELECT Firstname, Lastname, Start, End FROM Members_Tbl WHERE End = '" + today + "' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            MEMBERS_TBL.setModel(DbUtils.resultSetToTableModel(rs));
            
             pst.close();
             rs.close();
        } catch (SQLException e) {
          
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SIDEBAR = new javax.swing.JPanel();
        ADD_USER = new javax.swing.JButton();
        ADD_MEMBER = new javax.swing.JButton();
        MONTH_REPORT = new javax.swing.JButton();
        LBL_Register = new javax.swing.JLabel();
        LBL_AddMember = new javax.swing.JLabel();
        LBL_MonthlyReports = new javax.swing.JLabel();
        MEMBERS = new javax.swing.JButton();
        LBL_MEMBERS = new javax.swing.JLabel();
        MEMBERS_INFORMATION = new javax.swing.JButton();
        LBL_MEMBERS1 = new javax.swing.JLabel();
        LBL_MEMBERSINFORMATION = new javax.swing.JLabel();
        TOPBAR = new javax.swing.JPanel();
        EXPIRED = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MEMBERS_TBL = new javax.swing.JTable();
        endfield = new javax.swing.JTextField();
        userid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("fitnesscamp");
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1414, 791));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize2.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Fitness Camp Information System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        SIDEBAR.setBackground(new java.awt.Color(51, 51, 51));

        ADD_USER.setBackground(new java.awt.Color(51, 51, 51));
        ADD_USER.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ADD_USER.setForeground(new java.awt.Color(255, 255, 255));
        ADD_USER.setText("REGISTER A USER");
        ADD_USER.setContentAreaFilled(false);
        ADD_USER.setOpaque(true);
        ADD_USER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADD_USERMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADD_USERMouseExited(evt);
            }
        });
        ADD_USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_USERActionPerformed(evt);
            }
        });

        ADD_MEMBER.setBackground(new java.awt.Color(51, 51, 51));
        ADD_MEMBER.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ADD_MEMBER.setForeground(new java.awt.Color(255, 255, 255));
        ADD_MEMBER.setText("ADD MEMBER");
        ADD_MEMBER.setContentAreaFilled(false);
        ADD_MEMBER.setMaximumSize(new java.awt.Dimension(137, 29));
        ADD_MEMBER.setMinimumSize(new java.awt.Dimension(137, 29));
        ADD_MEMBER.setOpaque(true);
        ADD_MEMBER.setPreferredSize(new java.awt.Dimension(137, 29));
        ADD_MEMBER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADD_MEMBERMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADD_MEMBERMouseExited(evt);
            }
        });
        ADD_MEMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_MEMBERActionPerformed(evt);
            }
        });

        MONTH_REPORT.setBackground(new java.awt.Color(51, 51, 51));
        MONTH_REPORT.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        MONTH_REPORT.setForeground(new java.awt.Color(255, 255, 255));
        MONTH_REPORT.setText("MONTHLY REPORTS");
        MONTH_REPORT.setContentAreaFilled(false);
        MONTH_REPORT.setOpaque(true);
        MONTH_REPORT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MONTH_REPORTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MONTH_REPORTMouseExited(evt);
            }
        });
        MONTH_REPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONTH_REPORTActionPerformed(evt);
            }
        });

        LBL_Register.setBackground(new java.awt.Color(51, 51, 51));
        LBL_Register.setOpaque(true);

        LBL_AddMember.setBackground(new java.awt.Color(51, 51, 51));
        LBL_AddMember.setOpaque(true);

        LBL_MonthlyReports.setBackground(new java.awt.Color(51, 51, 51));
        LBL_MonthlyReports.setOpaque(true);

        MEMBERS.setBackground(new java.awt.Color(51, 51, 51));
        MEMBERS.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        MEMBERS.setForeground(new java.awt.Color(255, 255, 255));
        MEMBERS.setText("MEMBERS");
        MEMBERS.setContentAreaFilled(false);
        MEMBERS.setOpaque(true);
        MEMBERS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MEMBERSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MEMBERSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MEMBERSMouseExited(evt);
            }
        });
        MEMBERS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEMBERSActionPerformed(evt);
            }
        });

        LBL_MEMBERS.setBackground(new java.awt.Color(51, 51, 51));
        LBL_MEMBERS.setOpaque(true);

        MEMBERS_INFORMATION.setBackground(new java.awt.Color(51, 51, 51));
        MEMBERS_INFORMATION.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        MEMBERS_INFORMATION.setForeground(new java.awt.Color(255, 255, 255));
        MEMBERS_INFORMATION.setText("Members Information");
        MEMBERS_INFORMATION.setContentAreaFilled(false);
        MEMBERS_INFORMATION.setOpaque(true);
        MEMBERS_INFORMATION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MEMBERS_INFORMATIONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MEMBERS_INFORMATIONMouseExited(evt);
            }
        });
        MEMBERS_INFORMATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEMBERS_INFORMATIONActionPerformed(evt);
            }
        });

        LBL_MEMBERS1.setBackground(new java.awt.Color(51, 51, 51));
        LBL_MEMBERS1.setOpaque(true);

        LBL_MEMBERSINFORMATION.setBackground(new java.awt.Color(51, 51, 51));
        LBL_MEMBERSINFORMATION.setOpaque(true);

        javax.swing.GroupLayout SIDEBARLayout = new javax.swing.GroupLayout(SIDEBAR);
        SIDEBAR.setLayout(SIDEBARLayout);
        SIDEBARLayout.setHorizontalGroup(
            SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SIDEBARLayout.createSequentialGroup()
                .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MONTH_REPORT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(ADD_MEMBER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ADD_USER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MEMBERS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(MEMBERS_INFORMATION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SIDEBARLayout.createSequentialGroup()
                        .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBL_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_MonthlyReports, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SIDEBARLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_MEMBERS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_MEMBERSINFORMATION, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SIDEBARLayout.createSequentialGroup()
                    .addContainerGap(234, Short.MAX_VALUE)
                    .addComponent(LBL_MEMBERS1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        SIDEBARLayout.setVerticalGroup(
            SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SIDEBARLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBL_Register, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(ADD_USER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ADD_MEMBER, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(LBL_AddMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MONTH_REPORT, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(LBL_MonthlyReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBL_MEMBERS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MEMBERS, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MEMBERS_INFORMATION, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(LBL_MEMBERSINFORMATION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(366, Short.MAX_VALUE))
            .addGroup(SIDEBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SIDEBARLayout.createSequentialGroup()
                    .addGap(329, 329, 329)
                    .addComponent(LBL_MEMBERS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(322, 322, 322)))
        );

        TOPBAR.setBackground(new java.awt.Color(219, 219, 219));

        EXPIRED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXPIREDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TOPBARLayout = new javax.swing.GroupLayout(TOPBAR);
        TOPBAR.setLayout(TOPBARLayout);
        TOPBARLayout.setHorizontalGroup(
            TOPBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TOPBARLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(EXPIRED, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TOPBARLayout.setVerticalGroup(
            TOPBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TOPBARLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EXPIRED, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        DynamicPanel.setBackground(new java.awt.Color(250, 250, 250));

        MEMBERS_TBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Start", "End"
            }
        ));
        MEMBERS_TBL.setToolTipText("");
        jScrollPane1.setViewportView(MEMBERS_TBL);

        jButton3.setText("RENEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DELETE");

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DynamicPanelLayout.createSequentialGroup()
                .addGroup(DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DynamicPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2))
                    .addGroup(DynamicPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DynamicPanelLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3))
                        .addGap(73, 73, 73)
                        .addGroup(DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(endfield, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(561, Short.MAX_VALUE))
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DynamicPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DynamicPanelLayout.createSequentialGroup()
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(endfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(DynamicPanelLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(SIDEBAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TOPBAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SIDEBAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TOPBAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getAccessibleContext().setAccessibleName("Main menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2MouseClicked

    private void ADD_USERMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD_USERMouseEntered
        ADD_USER.setBackground(new Color(92, 92, 92));
    }//GEN-LAST:event_ADD_USERMouseEntered

    private void ADD_USERMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD_USERMouseExited
        ADD_USER.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ADD_USERMouseExited

    private void ADD_MEMBERMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD_MEMBERMouseEntered
        ADD_MEMBER.setBackground(new Color(92, 92, 92));
    }//GEN-LAST:event_ADD_MEMBERMouseEntered

    private void MONTH_REPORTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MONTH_REPORTMouseEntered
        MONTH_REPORT.setBackground(new Color(92, 92, 92));
    }//GEN-LAST:event_MONTH_REPORTMouseEntered

    private void ADD_MEMBERMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD_MEMBERMouseExited
        ADD_MEMBER.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ADD_MEMBERMouseExited

    private void MONTH_REPORTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MONTH_REPORTMouseExited
        MONTH_REPORT.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_MONTH_REPORTMouseExited

    private void ADD_USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_USERActionPerformed
        LBL_Register.setBackground(new Color(92, 92, 92));

        LBL_AddMember.setBackground(new Color(51, 51, 51));
        LBL_MonthlyReports.setBackground(new Color(51, 51, 51));
        LBL_MEMBERS.setBackground(new Color(51, 51, 51));
        LBL_MEMBERSINFORMATION.setBackground(new Color(51, 51, 51));

        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_ADD_USERActionPerformed

    private void ADD_MEMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_MEMBERActionPerformed
        LBL_AddMember.setBackground(new Color(92, 92, 92));

        LBL_Register.setBackground(new Color(51, 51, 51));
        LBL_MonthlyReports.setBackground(new Color(51, 51, 51));
        LBL_MEMBERS.setBackground(new Color(51, 51, 51));
        LBL_MEMBERSINFORMATION.setBackground(new Color(51, 51, 51));

        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_ADD_MEMBERActionPerformed

    private void MONTH_REPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONTH_REPORTActionPerformed
        LBL_MonthlyReports.setBackground(new Color(92, 92, 92));

        LBL_Register.setBackground(new Color(51, 51, 51));
        LBL_AddMember.setBackground(new Color(51, 51, 51));
        LBL_MEMBERS.setBackground(new Color(51, 51, 51));
        LBL_MEMBERSINFORMATION.setBackground(new Color(51, 51, 51));

        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_MONTH_REPORTActionPerformed

    private void MEMBERSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEMBERSMouseEntered
        MEMBERS.setBackground(new Color(92, 92, 92));
    }//GEN-LAST:event_MEMBERSMouseEntered

    private void MEMBERSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEMBERSMouseExited
        MEMBERS.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_MEMBERSMouseExited

    private void MEMBERSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEMBERSActionPerformed
        LBL_MEMBERS.setBackground(new Color(92, 92, 92));

        LBL_Register.setBackground(new Color(51, 51, 51));
        LBL_AddMember.setBackground(new Color(51, 51, 51));
        LBL_MonthlyReports.setBackground(new Color(51, 51, 51));
        LBL_MEMBERSINFORMATION.setBackground(new Color(51, 51, 51));

        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
    }//GEN-LAST:event_MEMBERSActionPerformed

    private void MEMBERS_INFORMATIONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEMBERS_INFORMATIONMouseEntered
        MEMBERS_INFORMATION.setBackground(new Color(92, 92, 92));
    }//GEN-LAST:event_MEMBERS_INFORMATIONMouseEntered

    private void MEMBERS_INFORMATIONMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEMBERS_INFORMATIONMouseExited
        MEMBERS_INFORMATION.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_MEMBERS_INFORMATIONMouseExited

    private void MEMBERS_INFORMATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEMBERS_INFORMATIONActionPerformed
        LBL_MEMBERSINFORMATION.setBackground(new Color(92, 92, 92));

        LBL_Register.setBackground(new Color(51, 51, 51));
        LBL_AddMember.setBackground(new Color(51, 51, 51));
        LBL_MonthlyReports.setBackground(new Color(51, 51, 51));
        LBL_MEMBERS.setBackground(new Color(51, 51, 51));

        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
    }//GEN-LAST:event_MEMBERS_INFORMATIONActionPerformed

    private void EXPIREDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXPIREDActionPerformed
        EXPIRED a = new EXPIRED();
        a.setVisible(true);
    }//GEN-LAST:event_EXPIREDActionPerformed

    private void MEMBERSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEMBERSMouseClicked
        Members test = new Members();
        test.members_table_update();
    }//GEN-LAST:event_MEMBERSMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_MEMBER;
    private javax.swing.JButton ADD_USER;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton EXPIRED;
    private javax.swing.JLabel LBL_AddMember;
    private javax.swing.JLabel LBL_MEMBERS;
    private javax.swing.JLabel LBL_MEMBERS1;
    private javax.swing.JLabel LBL_MEMBERSINFORMATION;
    private javax.swing.JLabel LBL_MonthlyReports;
    private javax.swing.JLabel LBL_Register;
    private javax.swing.JButton MEMBERS;
    private javax.swing.JButton MEMBERS_INFORMATION;
    private javax.swing.JTable MEMBERS_TBL;
    private javax.swing.JButton MONTH_REPORT;
    private javax.swing.JPanel SIDEBAR;
    private javax.swing.JPanel TOPBAR;
    private javax.swing.JTextField endfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
